/**
 * EditorView (SPEC.md §5.4): the open→edit→save roundtrip preserves
 * passthrough Modelfile content, and the raw/form panes stay in sync both
 * directions.
 */
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { EditorView } from "./EditorView";
import { TopNav } from "../ui/TopNav";
import { RemudaProvider } from "../ui/state";
import { FakeClient, makeModel } from "../ui/test/FakeClient";

const FIXTURE_MODELFILE = `# generated by a human, not Remuda
FROM llama3.1:8b

LICENSE """
Copyright someone. All rights reserved.
"""

SYSTEM """You are a concise, friendly assistant."""

PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER stop "</s>"
`;

function fixtureClient(overrides: Partial<ConstructorParameters<typeof FakeClient>[0]> = {}) {
  return new FakeClient({
    models: [makeModel({ tag: "llama3.1:8b", isLoaded: true })],
    modelfile: FIXTURE_MODELFILE,
    ...overrides,
  });
}

async function openEditorFor(client: FakeClient) {
  render(
    <RemudaProvider client={client} pollIntervalMs={1_000_000}>
      <TopNav />
      <EditorView />
    </RemudaProvider>,
  );
  fireEvent.click(await screen.findByLabelText("Edit llama3.1:8b's Modelfile"));
  await screen.findByLabelText("Raw Modelfile");
}

describe("EditorView", () => {
  beforeEach(() => {
    vi.spyOn(window, "confirm").mockReturnValue(true);
  });
  afterEach(() => {
    vi.restoreAllMocks();
  });

  it("open → edit → save preserves passthrough content (comments, LICENSE) in the create request", async () => {
    const client = fixtureClient();
    await openEditorFor(client);

    const raw = screen.getByLabelText("Raw Modelfile") as HTMLTextAreaElement;
    expect(raw.value).toContain("generated by a human");
    expect(raw.value).toContain("LICENSE");
    expect(screen.getByText(/Advanced content preserved/)).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "Save" }));

    await waitFor(() => expect(client.createCalls).toHaveLength(1));
    const request = client.createCalls[0]!.request;
    expect(client.createCalls[0]!.name).toBe("llama3.1:8b");
    expect(request.rawModelfile).toContain("generated by a human");
    expect(request.rawModelfile).toContain("LICENSE");
    expect(request.rawModelfile).toContain("Copyright someone");
  });

  it("a form edit (System prompt) regenerates the raw pane", async () => {
    const client = fixtureClient();
    await openEditorFor(client);

    fireEvent.change(screen.getByLabelText(/System prompt/), {
      target: { value: "Be extremely terse." },
    });

    const raw = screen.getByLabelText("Raw Modelfile") as HTMLTextAreaElement;
    await waitFor(() => expect(raw.value).toContain("Be extremely terse."));
    // Unmanaged content is still there — a form edit never drops it.
    expect(raw.value).toContain("LICENSE");
  });

  it("a raw edit re-parses into the form", async () => {
    const client = fixtureClient();
    await openEditorFor(client);

    const raw = screen.getByLabelText("Raw Modelfile") as HTMLTextAreaElement;
    fireEvent.change(raw, {
      target: { value: raw.value.replace("FROM llama3.1:8b", "FROM mistral:7b") },
    });

    await waitFor(() =>
      expect((screen.getByLabelText(/Base model/) as HTMLSelectElement).value).toBe("mistral:7b"),
    );
  });
});
