import { describe, expect, it } from "vitest";
import { passthroughKinds } from "./passthrough";

describe("passthroughKinds", () => {
  it("finds nothing beyond FROM/SYSTEM/managed PARAMETERs", () => {
    const text = `FROM llama3.1:8b\n\nSYSTEM """Be helpful."""\n\nPARAMETER temperature 0.7\nPARAMETER stop "</s>"\n`;
    expect(passthroughKinds(text)).toEqual([]);
  });

  it("flags comments, LICENSE, and unmanaged PARAMETER keys", () => {
    const text = [
      "# generated by a human",
      "FROM llama3.1:8b",
      "",
      'LICENSE """',
      "All rights reserved.",
      '"""',
      "",
      "PARAMETER mirostat 2",
    ].join("\n");
    const kinds = passthroughKinds(text);
    expect(kinds).toContain("comments");
    expect(kinds).toContain("LICENSE");
    expect(kinds).toContain("PARAMETER mirostat");
  });
});
